Registrar/Models/Course.cs
using System.Collections.Generic;

namespace Registrar.Models
{
  public class Course
  {
    public Course()
    {
      this.Students = new HashSet<CourseStudent>();
    }

    public int CourseId { get; set; }
    public string CourseName { get; set; }
    public string CourseNumber { get; set; }
    public virtual ICollection<CourseStudent> Students { get; set; }
  }
}

Registrar/Models/CourseStudent.cs
namespace Registrar.Models
{
  public class CourseStudent
  {
    public int CourseStudentId { get; set; }
    public int StudentId { get; set; }
    public int CourseId { get; set; }
    public Student Student { get; set; }
    public Course Course { get; set; }
  }
}

Registrar/Models/Department.cs
using System.Collections.Generic;

namespace Registrar.Models
{
  public class Department
  {
    public Department()
    {
      this.Courses = new HashSet<Course>();
      this.Students = new HashSet<Student>();
    }

    public int DepartmentId { get; set; }
    public string DepartmentName { get; set; }
    public ICollection<Course> Courses { get; }
    public ICollection<Student> Students { get; }
  }
}

Registrar/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Registrar.Models
{
  public class RegistrarContextFactory : IDesignTimeDbContextFactory<RegistrarContext>
  {

    RegistrarContext IDesignTimeDbContextFactory<RegistrarContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<RegistrarContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new RegistrarContext(builder.Options);
    }
  }
}

Registrar/Models/RegistrarContext.cs
using Microsoft.EntityFrameworkCore;

namespace Registrar.Models
{
  public class RegistrarContext : DbContext
  {
    public virtual DbSet<Course> Courses { get; set; }
    public DbSet<Student> Students { get; set; }
    public DbSet<CourseStudent> CourseStudent { get; set; }
    public DbSet<Department> Departments { get; set; }
    public RegistrarContext(DbContextOptions options) : base(options) { }
  }
}

Registrar/Models/Student.cs
using System;
using System.Collections.Generic;

namespace Registrar.Models
{
  public class Student
  {
    public Student()
    {
      this.Courses = new HashSet<CourseStudent>();
    }

    public int StudentId { get; set; }
    public string Name { get; set; }
    public DateTime EnrollmentDate { get; set; }
    public ICollection<CourseStudent> Courses { get; }
  }
}

Registrar/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;

namespace Registrar.Controllers
{
  public class CoursesController : Controller
  {
    private readonly RegistrarContext _db;

    public CoursesController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Course> model = _db.Courses.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Course course)
    {
      _db.Courses.Add(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisCourse = _db.Courses
        .Include(course => course.Students)
        .ThenInclude(join => join.Student)
        .FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }
  }
}

Registrar/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;

namespace Registrar.Models
{
  public class DepartmentsController : Controller
  {
    private readonly RegistrarContext _db;

    public DepartmentsController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Department> model = _db.Departments.ToList();
      return View(model);
    }
    
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Department department)
    {
      _db.Departments.Add(department);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Registrar/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Registrar.Controllers
{
  public class HomeController : Controller
  {
    public ActionResult Index()
    {
      return View();
    }
  }
}

Registrar/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;

namespace Registrar.Controllers
{
  public class StudentsController : Controller
  {
    private readonly RegistrarContext _db;

    public StudentsController (RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Students.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Student student, int CourseId)
    {
      _db.Students.Add(student);
      if(CourseId != 0 && !_db.CourseStudent.Any(x => x.StudentId == student.StudentId && x.CourseId == CourseId))
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisStudent = _db.Students
        .Include(student => student.Courses)
        .ThenInclude(join => join.Course)
        .FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }
    
    public ActionResult Edit(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult Edit(Student student, int CourseId)
    {
      if (CourseId != 0 && !_db.CourseStudent.Any(x => x.CourseId == CourseId && x.StudentId == student.StudentId))
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.Entry(student).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddCourse(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult AddCourse(Student student, int CourseId)
    {
      if (CourseId != 0 && !_db.CourseStudent.Any(x => x.CourseId == CourseId && x.StudentId == student.StudentId))
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Registrar/Views/Courses/Create.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Course

<h1>Add a new course</h1>

@using(Html.BeginForm())
{
  @Html.LabelFor(model => model.CourseName)
  @Html.TextBoxFor(model => model.CourseName)

  @Html.LabelFor(model => model.CourseNumber)
  @Html.TextBoxFor(model => model.CourseNumber)

  <input type="submit" value="Add new course"/>
}

<p>@Html.ActionLink("View all courses", "Index")</p>

Registrar/Views/Courses/Details.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Course;

<h2>Course Details</h2>
<br>
<h3>@Html.DisplayFor(model => model.CourseName)</h3>
<br>
<h4>Course Number: @Html.DisplayFor(model => model.CourseNumber)</h4>

@if (@Model.Students.Count == 0)
{
  <p>No students enrolled</p>
}
else
{
  <h4>Students enrolled in the class:</h4>
  <ul>
  @foreach(var join in Model.Students)
  {
    <li>@join.Student.Name</li>
  }
  </ul>
}

<p>@Html.ActionLink("Back to course list", "Index")</p>

Registrar/Views/Courses/Index.cshtml
@{
  Layout = "_Layout";
}

@using Registrar.Models;
@model List<Registrar.Models.Course>;

<h1>Courses</h1>

@if(@Model.Count == 0)
{
  <h3>There are no courses.</h3>
}
else
{
  <ul>
    @foreach (Course course in Model)
    {
      <li>@Html.ActionLink($"{course.CourseName}", "Details", new { id = course.CourseId})</li>
    }
  </ul>
}

<P>@Html.ActionLink("Add new course", "Create")</P>
<P>@Html.ActionLink("Home", "Index", "Home")</P>

Registrar/Views/Departments/Create.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Department

<h1>Add a new department</h1>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.DepartmentName)
  @Html.TextBoxFor(model => model.DepartmentName)
  <input type="submit" value="Add a new department"/>
}

<p>@Html.ActionLink("View all departments", "Index")</p>

Registrar/Views/Departments/Index.cshtml
@{
  Layout = "_Layout";
}

@using Registrar.Models;
@model List<Registrar.Models.Department>

<h1>Departments</h1>

@if(@Model.Count == 0)
{
  <h3>There are no departments.</h3>
}
else
{
  <ul>
    @foreach (Department department in Model)
    {
      <li>@Html.ActionLink($"{department.DepartmentName}", "Details", new { id = department.DepartmentId})</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add a new department", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Registrar/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>University Registrar</h1>
<p>@Html.ActionLink("View courses", "Index", "Courses")</p>
<p>@Html.ActionLink("View students", "Index", "Students")</p>
<p>@Html.ActionLink("View departments", "Index", "Departments")</p>

Registrar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>University Registrar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

Registrar/Views/Students/AddCourse.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Student

<h2>Add a course</h2>

<h4>Add a course to this student: @Html.DisplayFor(model => model.Name)</h4>

@using(Html.BeginForm())
{
  @Html.HiddenFor(model => model.StudentId)

  @Html.Label("Choose a course")
  @Html.DropDownList("CourseId")

  <input type="submit" value="Save">
}

<p>@Html.ActionLink("Back to student list", "Index")</p>

Registrar/Views/Students/Create.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Student

<h1>Add a new student</h1>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.Label("Date of Enrollment")
  @Html.TextBox("EnrollmentDate", null, new { type="date"})

  @Html.Label("Select course")
  @Html.DropDownList("CourseId")

  <input type="submit" value="Add new student" class="btn btn-primary"/>
}

<p>@Html.ActionLink("Show all students", "Index")</p>

Registrar/Views/Students/Details.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Student

<h2>Student Details</h2>
<br>
<h3>@Html.DisplayFor(model => model.Name)</h3>
<br>
<h4>@Html.DisplayNameFor(model => model.EnrollmentDate): @Html.DisplayFor(model => model.EnrollmentDate)</h4>

@if(@Model.Courses.Count == 0)
{
  <p>This student doesn't have any courses.</p>
}
else
{
  <h4>Courses this student is taking:</h4>
  <ul>
    @foreach (var join in Model.Courses)
    {
      <li>@join.Course.CourseNumber | @join.Course.CourseName</li>
    }
  </ul>
}
<p>@Html.ActionLink("Edit student", "Edit", new { id = Model.StudentId})</p>
<p>@Html.ActionLink("Add course to schedule", "AddCourse", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Back to Student List", "Index")</p>

Registrar/Views/Students/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Student

<h2>Edit</h2>

<h4>Edit this student: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StudentId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.Label("Date of Enrollment")
  @Html.EditorFor(model => model.EnrollmentDate)

  <input type="submit" value="Save" class="btn btn-primary"/>
}

<p>@Html.ActionLink("Back to student list", "Index")</p>

Registrar/Views/Students/Index.cshtml
@{
  Layout = "_Layout";
}

@using Registrar.Models;
@model List<Registrar.Models.Student>;

<h1>Students</h1>

@if(@Model.Count == 0)
{
  <h3>There are no students</h3>
}
else
{
  <ul>
  @foreach (Student student in Model)
  {
    <li>@Html.ActionLink($"{student.Name}", "Details", new { id = student.StudentId})</li>
  }
  </ul>
}

<p>@Html.ActionLink("Add a new student", "Create")</p>
<P>@Html.ActionLink("Home", "Index", "Home")</P>